// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {models} from '../models';
import {sftp} from '../models';

export function CloseSession(arg1:string):Promise<void>;

export function ConnectSSH(arg1:string):Promise<string>;

export function CreateConnection(arg1:models.Connection):Promise<void>;

export function CreateFolder(arg1:string):Promise<void>;

export function DeleteConnection(arg1:string):Promise<void>;

export function DeleteFolder(arg1:string):Promise<void>;

export function GetConnectionByID(arg1:string):Promise<models.Connection>;

export function GetConnections():Promise<Array<models.Connection>>;

export function GetFolders():Promise<Array<models.Folder>>;

export function ListDirectory(arg1:string,arg2:string):Promise<Array<sftp.FileItem>>;

export function ListSessions():Promise<Array<string>>;

export function ResizeTerminal(arg1:string,arg2:number,arg3:number):Promise<void>;

export function SendInput(arg1:string,arg2:string):Promise<void>;

export function UpdateConnection(arg1:models.Connection):Promise<void>;

export function UpdateFolder(arg1:string,arg2:string):Promise<void>;
