// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddTunnel(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['AddTunnel'](arg1, arg2, arg3, arg4);
}

export function CloseSession(arg1) {
  return window['go']['main']['App']['CloseSession'](arg1);
}

export function ConnectSSH(arg1) {
  return window['go']['main']['App']['ConnectSSH'](arg1);
}

export function CreateConnection(arg1) {
  return window['go']['main']['App']['CreateConnection'](arg1);
}

export function CreateFolder(arg1) {
  return window['go']['main']['App']['CreateFolder'](arg1);
}

export function CreateRemoteDirectory(arg1, arg2) {
  return window['go']['main']['App']['CreateRemoteDirectory'](arg1, arg2);
}

export function DeleteConnection(arg1) {
  return window['go']['main']['App']['DeleteConnection'](arg1);
}

export function DeleteFolder(arg1) {
  return window['go']['main']['App']['DeleteFolder'](arg1);
}

export function DeleteRemoteFile(arg1, arg2) {
  return window['go']['main']['App']['DeleteRemoteFile'](arg1, arg2);
}

export function DeleteTunnel(arg1, arg2) {
  return window['go']['main']['App']['DeleteTunnel'](arg1, arg2);
}

export function DownloadFile(arg1, arg2, arg3) {
  return window['go']['main']['App']['DownloadFile'](arg1, arg2, arg3);
}

export function EditTunnel(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['EditTunnel'](arg1, arg2, arg3, arg4, arg5);
}

export function GetConnectionByID(arg1) {
  return window['go']['main']['App']['GetConnectionByID'](arg1);
}

export function GetConnections() {
  return window['go']['main']['App']['GetConnections']();
}

export function GetDatabases(arg1) {
  return window['go']['main']['App']['GetDatabases'](arg1);
}

export function GetDockerContainers(arg1) {
  return window['go']['main']['App']['GetDockerContainers'](arg1);
}

export function GetFolders() {
  return window['go']['main']['App']['GetFolders']();
}

export function GetListeningPorts(arg1) {
  return window['go']['main']['App']['GetListeningPorts'](arg1);
}

export function GetSystemStats(arg1) {
  return window['go']['main']['App']['GetSystemStats'](arg1);
}

export function GetTunnels(arg1) {
  return window['go']['main']['App']['GetTunnels'](arg1);
}

export function ListDirectory(arg1, arg2) {
  return window['go']['main']['App']['ListDirectory'](arg1, arg2);
}

export function ListSessions() {
  return window['go']['main']['App']['ListSessions']();
}

export function OpenDockerLogWindow(arg1, arg2, arg3) {
  return window['go']['main']['App']['OpenDockerLogWindow'](arg1, arg2, arg3);
}

export function ReadRemoteFile(arg1, arg2) {
  return window['go']['main']['App']['ReadRemoteFile'](arg1, arg2);
}

export function RenameRemoteFile(arg1, arg2, arg3) {
  return window['go']['main']['App']['RenameRemoteFile'](arg1, arg2, arg3);
}

export function ResizeTerminal(arg1, arg2, arg3) {
  return window['go']['main']['App']['ResizeTerminal'](arg1, arg2, arg3);
}

export function SaveRemoteFile(arg1, arg2, arg3) {
  return window['go']['main']['App']['SaveRemoteFile'](arg1, arg2, arg3);
}

export function SendInput(arg1, arg2) {
  return window['go']['main']['App']['SendInput'](arg1, arg2);
}

export function StartDockerLogs(arg1, arg2) {
  return window['go']['main']['App']['StartDockerLogs'](arg1, arg2);
}

export function StopDockerLogs(arg1, arg2) {
  return window['go']['main']['App']['StopDockerLogs'](arg1, arg2);
}

export function ToggleContainer(arg1, arg2, arg3) {
  return window['go']['main']['App']['ToggleContainer'](arg1, arg2, arg3);
}

export function ToggleTunnel(arg1, arg2, arg3, arg4, arg5, arg6) {
  return window['go']['main']['App']['ToggleTunnel'](arg1, arg2, arg3, arg4, arg5, arg6);
}

export function UpdateConnection(arg1) {
  return window['go']['main']['App']['UpdateConnection'](arg1);
}

export function UpdateFolder(arg1, arg2) {
  return window['go']['main']['App']['UpdateFolder'](arg1, arg2);
}

export function UploadFile(arg1, arg2) {
  return window['go']['main']['App']['UploadFile'](arg1, arg2);
}
