// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {models} from '../models';
import {sftp} from '../models';

export function AddTunnel(arg1:string,arg2:number,arg3:string,arg4:number):Promise<models.TunnelInfo>;

export function CloseSession(arg1:string):Promise<void>;

export function ConnectSSH(arg1:string):Promise<string>;

export function CreateConnection(arg1:models.Connection):Promise<void>;

export function CreateFolder(arg1:string):Promise<void>;

export function CreateRemoteDirectory(arg1:string,arg2:string):Promise<void>;

export function DeleteConnection(arg1:string):Promise<void>;

export function DeleteFolder(arg1:string):Promise<void>;

export function DeleteRemoteFile(arg1:string,arg2:string):Promise<void>;

export function DeleteTunnel(arg1:string,arg2:string):Promise<void>;

export function DownloadFile(arg1:string,arg2:string,arg3:string):Promise<void>;

export function EditTunnel(arg1:string,arg2:string,arg3:number,arg4:string,arg5:number):Promise<models.TunnelInfo>;

export function GetConnectionByID(arg1:string):Promise<models.Connection>;

export function GetConnections():Promise<Array<models.Connection>>;

export function GetDockerContainers(arg1:string):Promise<Array<models.DockerContainer>>;

export function GetFolders():Promise<Array<models.Folder>>;

export function GetTunnels(arg1:string):Promise<Array<models.TunnelInfo>>;

export function ListDirectory(arg1:string,arg2:string):Promise<Array<sftp.FileItem>>;

export function ListSessions():Promise<Array<string>>;

export function ReadRemoteFile(arg1:string,arg2:string):Promise<string>;

export function RenameRemoteFile(arg1:string,arg2:string,arg3:string):Promise<void>;

export function ResizeTerminal(arg1:string,arg2:number,arg3:number):Promise<void>;

export function SaveRemoteFile(arg1:string,arg2:string,arg3:string):Promise<void>;

export function SendInput(arg1:string,arg2:string):Promise<void>;

export function ToggleContainer(arg1:string,arg2:string,arg3:string):Promise<string>;

export function ToggleTunnel(arg1:string,arg2:string,arg3:number,arg4:string,arg5:number,arg6:boolean):Promise<void>;

export function UpdateConnection(arg1:models.Connection):Promise<void>;

export function UpdateFolder(arg1:string,arg2:string):Promise<void>;

export function UploadFile(arg1:string,arg2:string):Promise<void>;
