// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CloseSession(arg1:string):Promise<void>;

export function ConnectSSH():Promise<string>;

export function ListSessions():Promise<Array<string>>;

export function ResizeTerminal(arg1:string,arg2:number,arg3:number):Promise<void>;

export function SendInput(arg1:string,arg2:string):Promise<void>;
