// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

export class Connection {
    "id": string;
    "folderId"?: string | null;
    "name": string;
    "host": string;
    "port": number;
    "username": string;
    "authType": string;
    "password"?: string | null;
    "privateKeyPath"?: string | null;
    "color"?: string | null;

    /** Creates a new Connection instance. */
    constructor($$source: Partial<Connection> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("host" in $$source)) {
            this["host"] = "";
        }
        if (!("port" in $$source)) {
            this["port"] = 0;
        }
        if (!("username" in $$source)) {
            this["username"] = "";
        }
        if (!("authType" in $$source)) {
            this["authType"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Connection instance from a string or object.
     */
    static createFrom($$source: any = {}): Connection {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Connection($$parsedSource as Partial<Connection>);
    }
}

export class DatabaseInfo {
    "name": string;
    "port": number;
    "address": string;

    /**
     * "system" | "docker"
     */
    "source": string;

    /**
     * nombre del contenedor si es docker
     */
    "container": string;

    /**
     * imagen docker si aplica
     */
    "image": string;

    /** Creates a new DatabaseInfo instance. */
    constructor($$source: Partial<DatabaseInfo> = {}) {
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("port" in $$source)) {
            this["port"] = 0;
        }
        if (!("address" in $$source)) {
            this["address"] = "";
        }
        if (!("source" in $$source)) {
            this["source"] = "";
        }
        if (!("container" in $$source)) {
            this["container"] = "";
        }
        if (!("image" in $$source)) {
            this["image"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new DatabaseInfo instance from a string or object.
     */
    static createFrom($$source: any = {}): DatabaseInfo {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new DatabaseInfo($$parsedSource as Partial<DatabaseInfo>);
    }
}

export class DockerContainer {
    "id": string;
    "names": string;
    "image": string;
    "status": string;
    "state": string;
    "ports": string;

    /** Creates a new DockerContainer instance. */
    constructor($$source: Partial<DockerContainer> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("names" in $$source)) {
            this["names"] = "";
        }
        if (!("image" in $$source)) {
            this["image"] = "";
        }
        if (!("status" in $$source)) {
            this["status"] = "";
        }
        if (!("state" in $$source)) {
            this["state"] = "";
        }
        if (!("ports" in $$source)) {
            this["ports"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new DockerContainer instance from a string or object.
     */
    static createFrom($$source: any = {}): DockerContainer {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new DockerContainer($$parsedSource as Partial<DockerContainer>);
    }
}

export class Folder {
    "id": string;
    "name": string;
    "parentId"?: string | null;

    /** Creates a new Folder instance. */
    constructor($$source: Partial<Folder> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("name" in $$source)) {
            this["name"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Folder instance from a string or object.
     */
    static createFrom($$source: any = {}): Folder {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Folder($$parsedSource as Partial<Folder>);
    }
}

export class PortInfo {
    "port": number;
    "address": string;
    "process": string;
    "proto": string;

    /** Creates a new PortInfo instance. */
    constructor($$source: Partial<PortInfo> = {}) {
        if (!("port" in $$source)) {
            this["port"] = 0;
        }
        if (!("address" in $$source)) {
            this["address"] = "";
        }
        if (!("process" in $$source)) {
            this["process"] = "";
        }
        if (!("proto" in $$source)) {
            this["proto"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new PortInfo instance from a string or object.
     */
    static createFrom($$source: any = {}): PortInfo {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new PortInfo($$parsedSource as Partial<PortInfo>);
    }
}

export class QueryColumn {
    "name": string;
    "dataType": string;
    "nullable": boolean;
    "default": string;
    "key": string;

    /** Creates a new QueryColumn instance. */
    constructor($$source: Partial<QueryColumn> = {}) {
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("dataType" in $$source)) {
            this["dataType"] = "";
        }
        if (!("nullable" in $$source)) {
            this["nullable"] = false;
        }
        if (!("default" in $$source)) {
            this["default"] = "";
        }
        if (!("key" in $$source)) {
            this["key"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new QueryColumn instance from a string or object.
     */
    static createFrom($$source: any = {}): QueryColumn {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new QueryColumn($$parsedSource as Partial<QueryColumn>);
    }
}

export class QueryResult {
    "columns": string[];
    "rows": string[][];
    "rowCount": number;
    "error": string;

    /** Creates a new QueryResult instance. */
    constructor($$source: Partial<QueryResult> = {}) {
        if (!("columns" in $$source)) {
            this["columns"] = [];
        }
        if (!("rows" in $$source)) {
            this["rows"] = [];
        }
        if (!("rowCount" in $$source)) {
            this["rowCount"] = 0;
        }
        if (!("error" in $$source)) {
            this["error"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new QueryResult instance from a string or object.
     */
    static createFrom($$source: any = {}): QueryResult {
        const $$createField0_0 = $$createType0;
        const $$createField1_0 = $$createType1;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("columns" in $$parsedSource) {
            $$parsedSource["columns"] = $$createField0_0($$parsedSource["columns"]);
        }
        if ("rows" in $$parsedSource) {
            $$parsedSource["rows"] = $$createField1_0($$parsedSource["rows"]);
        }
        return new QueryResult($$parsedSource as Partial<QueryResult>);
    }
}

export class TunnelInfo {
    "id": string;
    "localPort": number;
    "remoteHost": string;
    "remotePort": number;
    "active": boolean;

    /** Creates a new TunnelInfo instance. */
    constructor($$source: Partial<TunnelInfo> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("localPort" in $$source)) {
            this["localPort"] = 0;
        }
        if (!("remoteHost" in $$source)) {
            this["remoteHost"] = "";
        }
        if (!("remotePort" in $$source)) {
            this["remotePort"] = 0;
        }
        if (!("active" in $$source)) {
            this["active"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new TunnelInfo instance from a string or object.
     */
    static createFrom($$source: any = {}): TunnelInfo {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new TunnelInfo($$parsedSource as Partial<TunnelInfo>);
    }
}

// Private type creation functions
const $$createType0 = $Create.Array($Create.Any);
const $$createType1 = $Create.Array($$createType0);
