// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as models$0 from "./backend/models/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as sftp$0 from "./backend/sftp/models.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * AddTunnel registra un nuevo túnel dinámico en la sesión actual
 * @param {string} sessionID
 * @param {number} localPort
 * @param {string} remoteHost
 * @param {number} remotePort
 * @returns {$CancellablePromise<models$0.TunnelInfo>}
 */
export function AddTunnel(sessionID, localPort, remoteHost, remotePort) {
    return $Call.ByID(1252415046, sessionID, localPort, remoteHost, remotePort).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

/**
 * @param {string} sessionID
 * @returns {$CancellablePromise<void>}
 */
export function CloseSession(sessionID) {
    return $Call.ByID(1620748453, sessionID);
}

/**
 * @param {string} connectionID
 * @returns {$CancellablePromise<string>}
 */
export function ConnectSSH(connectionID) {
    return $Call.ByID(2333793685, connectionID);
}

/**
 * @param {models$0.Connection} connection
 * @returns {$CancellablePromise<void>}
 */
export function CreateConnection(connection) {
    return $Call.ByID(1454115897, connection);
}

/**
 * @param {string} name
 * @returns {$CancellablePromise<void>}
 */
export function CreateFolder(name) {
    return $Call.ByID(1403526973, name);
}

/**
 * @param {string} sessionID
 * @param {string} path
 * @returns {$CancellablePromise<void>}
 */
export function CreateRemoteDirectory(sessionID, path) {
    return $Call.ByID(1468894482, sessionID, path);
}

/**
 * DbConnect opens an SSH-tunneled database connection using native Go drivers.
 * @param {string} sessionID
 * @param {string} dbType
 * @param {number} port
 * @param {string} user
 * @param {string} password
 * @returns {$CancellablePromise<string>}
 */
export function DbConnect(sessionID, dbType, port, user, password) {
    return $Call.ByID(925560863, sessionID, dbType, port, user, password);
}

/**
 * DbDisconnect closes all driver connections and cleans up resources.
 * @param {string} connID
 * @returns {$CancellablePromise<void>}
 */
export function DbDisconnect(connID) {
    return $Call.ByID(3946028753, connID);
}

/**
 * DbGetColumns returns column metadata using parameterized queries.
 * @param {string} connID
 * @param {string} database
 * @param {string} schema
 * @param {string} table
 * @returns {$CancellablePromise<models$0.QueryColumn[]>}
 */
export function DbGetColumns(connID, database, schema, table) {
    return $Call.ByID(417483548, connID, database, schema, table).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType2($result);
    }));
}

/**
 * DbListDatabases returns available databases over the SSH-tunneled connection.
 * @param {string} connID
 * @returns {$CancellablePromise<string[]>}
 */
export function DbListDatabases(connID) {
    return $Call.ByID(3180261039, connID).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType3($result);
    }));
}

/**
 * DbListSchemas returns schemas for a given database.
 * @param {string} connID
 * @param {string} database
 * @returns {$CancellablePromise<string[]>}
 */
export function DbListSchemas(connID, database) {
    return $Call.ByID(3889891413, connID, database).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType3($result);
    }));
}

/**
 * DbListTables returns tables for a database/schema using parameterized queries.
 * @param {string} connID
 * @param {string} database
 * @param {string} schema
 * @returns {$CancellablePromise<string[]>}
 */
export function DbListTables(connID, database, schema) {
    return $Call.ByID(3807366482, connID, database, schema).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType3($result);
    }));
}

/**
 * DbQuery executes arbitrary SQL and returns the result.
 * @param {string} connID
 * @param {string} database
 * @param {string} query
 * @returns {$CancellablePromise<models$0.QueryResult>}
 */
export function DbQuery(connID, database, query) {
    return $Call.ByID(2519177305, connID, database, query).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType4($result);
    }));
}

/**
 * @param {string} id
 * @returns {$CancellablePromise<void>}
 */
export function DeleteConnection(id) {
    return $Call.ByID(3428926502, id);
}

/**
 * @param {string} id
 * @returns {$CancellablePromise<void>}
 */
export function DeleteFolder(id) {
    return $Call.ByID(127207050, id);
}

/**
 * @param {string} sessionID
 * @param {string} path
 * @returns {$CancellablePromise<void>}
 */
export function DeleteRemoteFile(sessionID, path) {
    return $Call.ByID(3455570606, sessionID, path);
}

/**
 * DeleteTunnel elimina un túnel del registro (y lo apaga si está encendido)
 * @param {string} sessionID
 * @param {string} tunnelID
 * @returns {$CancellablePromise<void>}
 */
export function DeleteTunnel(sessionID, tunnelID) {
    return $Call.ByID(2127640780, sessionID, tunnelID);
}

/**
 * @param {string} sessionID
 * @param {string} remotePath
 * @param {string} localPath
 * @returns {$CancellablePromise<void>}
 */
export function DownloadFile(sessionID, remotePath, localPath) {
    return $Call.ByID(764734343, sessionID, remotePath, localPath);
}

/**
 * EditTunnel modifica los parámetros de un túnel existente
 * @param {string} sessionID
 * @param {string} tunnelID
 * @param {number} localPort
 * @param {string} remoteHost
 * @param {number} remotePort
 * @returns {$CancellablePromise<models$0.TunnelInfo>}
 */
export function EditTunnel(sessionID, tunnelID, localPort, remoteHost, remotePort) {
    return $Call.ByID(3536050427, sessionID, tunnelID, localPort, remoteHost, remotePort).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

/**
 * @param {string} id
 * @returns {$CancellablePromise<models$0.Connection | null>}
 */
export function GetConnectionByID(id) {
    return $Call.ByID(3650713919, id).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType6($result);
    }));
}

/**
 * @returns {$CancellablePromise<models$0.Connection[]>}
 */
export function GetConnections() {
    return $Call.ByID(1541859132).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType7($result);
    }));
}

/**
 * @param {string} sessionID
 * @returns {$CancellablePromise<models$0.DatabaseInfo[]>}
 */
export function GetDatabases(sessionID) {
    return $Call.ByID(2970679019, sessionID).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType9($result);
    }));
}

/**
 * @param {string} sessionID
 * @returns {$CancellablePromise<models$0.DockerContainer[]>}
 */
export function GetDockerContainers(sessionID) {
    return $Call.ByID(3789202067, sessionID).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType11($result);
    }));
}

/**
 * @returns {$CancellablePromise<models$0.Folder[]>}
 */
export function GetFolders() {
    return $Call.ByID(452841144).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType13($result);
    }));
}

/**
 * @param {string} sessionID
 * @returns {$CancellablePromise<models$0.PortInfo[]>}
 */
export function GetListeningPorts(sessionID) {
    return $Call.ByID(3826983416, sessionID).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType15($result);
    }));
}

/**
 * @param {string} sessionID
 * @returns {$CancellablePromise<$models.SystemStats | null>}
 */
export function GetSystemStats(sessionID) {
    return $Call.ByID(549671605, sessionID).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType17($result);
    }));
}

/**
 * GetTunnels obtiene la lista de túneles dinámicos guardados para la sesión activa
 * @param {string} sessionID
 * @returns {$CancellablePromise<models$0.TunnelInfo[]>}
 */
export function GetTunnels(sessionID) {
    return $Call.ByID(2458647734, sessionID).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType18($result);
    }));
}

/**
 * @param {string} sessionID
 * @param {string} path
 * @returns {$CancellablePromise<sftp$0.FileItem[]>}
 */
export function ListDirectory(sessionID, path) {
    return $Call.ByID(3882022436, sessionID, path).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType20($result);
    }));
}

/**
 * @returns {$CancellablePromise<string[]>}
 */
export function ListSessions() {
    return $Call.ByID(827108744).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType3($result);
    }));
}

/**
 * OpenDbExplorerWindow abre el explorador de BD en una ventana del navegador del sistema
 * @param {string} sessionID
 * @param {string} dbType
 * @param {number} port
 * @returns {$CancellablePromise<void>}
 */
export function OpenDbExplorerWindow(sessionID, dbType, port) {
    return $Call.ByID(2917079268, sessionID, dbType, port);
}

/**
 * OpenDockerLogWindow abre los logs del contenedor en una ventana del navegador del sistema
 * @param {string} sessionID
 * @param {string} containerID
 * @param {string} containerName
 * @returns {$CancellablePromise<void>}
 */
export function OpenDockerLogWindow(sessionID, containerID, containerName) {
    return $Call.ByID(1038673189, sessionID, containerID, containerName);
}

/**
 * @param {string} sessionID
 * @param {string} path
 * @returns {$CancellablePromise<string>}
 */
export function ReadRemoteFile(sessionID, path) {
    return $Call.ByID(4253671989, sessionID, path);
}

/**
 * @param {string} sessionID
 * @param {string} oldPath
 * @param {string} newPath
 * @returns {$CancellablePromise<void>}
 */
export function RenameRemoteFile(sessionID, oldPath, newPath) {
    return $Call.ByID(3344013991, sessionID, oldPath, newPath);
}

/**
 * @param {string} sessionID
 * @param {number} rows
 * @param {number} cols
 * @returns {$CancellablePromise<void>}
 */
export function ResizeTerminal(sessionID, rows, cols) {
    return $Call.ByID(1887984285, sessionID, rows, cols);
}

/**
 * @param {string} sessionID
 * @param {string} path
 * @param {string} content
 * @returns {$CancellablePromise<void>}
 */
export function SaveRemoteFile(sessionID, path, content) {
    return $Call.ByID(4146041056, sessionID, path, content);
}

/**
 * @param {string} sessionID
 * @param {string} data
 * @returns {$CancellablePromise<void>}
 */
export function SendInput(sessionID, data) {
    return $Call.ByID(2049385733, sessionID, data);
}

/**
 * StartDockerLogs abre docker logs -f en el contenedor y emite cada línea como evento Wails
 * @param {string} sessionID
 * @param {string} containerID
 * @returns {$CancellablePromise<void>}
 */
export function StartDockerLogs(sessionID, containerID) {
    return $Call.ByID(2915829348, sessionID, containerID);
}

/**
 * StopDockerLogs detiene el stream de logs cerrando la sesión SSH
 * @param {string} sessionID
 * @param {string} containerID
 * @returns {$CancellablePromise<void>}
 */
export function StopDockerLogs(sessionID, containerID) {
    return $Call.ByID(3177717606, sessionID, containerID);
}

/**
 * ToggleContainer ejecuta las acciones vitales: start, stop o restart
 * @param {string} sessionID
 * @param {string} containerID
 * @param {string} action
 * @returns {$CancellablePromise<string>}
 */
export function ToggleContainer(sessionID, containerID, action) {
    return $Call.ByID(2722533264, sessionID, containerID, action);
}

/**
 * ToggleTunnel enciende o apaga el túnel SSH local port forwarding de forma asíncrona
 * @param {string} sessionID
 * @param {string} tunnelID
 * @param {number} localPort
 * @param {string} remoteHost
 * @param {number} remotePort
 * @param {boolean} activate
 * @returns {$CancellablePromise<void>}
 */
export function ToggleTunnel(sessionID, tunnelID, localPort, remoteHost, remotePort, activate) {
    return $Call.ByID(1290322095, sessionID, tunnelID, localPort, remoteHost, remotePort, activate);
}

/**
 * @param {models$0.Connection} connection
 * @returns {$CancellablePromise<void>}
 */
export function UpdateConnection(connection) {
    return $Call.ByID(619964812, connection);
}

/**
 * @param {string} id
 * @param {string} name
 * @returns {$CancellablePromise<void>}
 */
export function UpdateFolder(id, name) {
    return $Call.ByID(4154189448, id, name);
}

/**
 * @param {string} sessionID
 * @param {string} remoteDirectory
 * @returns {$CancellablePromise<void>}
 */
export function UploadFile(sessionID, remoteDirectory) {
    return $Call.ByID(3284072274, sessionID, remoteDirectory);
}

// Private type creation functions
const $$createType0 = models$0.TunnelInfo.createFrom;
const $$createType1 = models$0.QueryColumn.createFrom;
const $$createType2 = $Create.Array($$createType1);
const $$createType3 = $Create.Array($Create.Any);
const $$createType4 = models$0.QueryResult.createFrom;
const $$createType5 = models$0.Connection.createFrom;
const $$createType6 = $Create.Nullable($$createType5);
const $$createType7 = $Create.Array($$createType5);
const $$createType8 = models$0.DatabaseInfo.createFrom;
const $$createType9 = $Create.Array($$createType8);
const $$createType10 = models$0.DockerContainer.createFrom;
const $$createType11 = $Create.Array($$createType10);
const $$createType12 = models$0.Folder.createFrom;
const $$createType13 = $Create.Array($$createType12);
const $$createType14 = models$0.PortInfo.createFrom;
const $$createType15 = $Create.Array($$createType14);
const $$createType16 = $models.SystemStats.createFrom;
const $$createType17 = $Create.Nullable($$createType16);
const $$createType18 = $Create.Array($$createType0);
const $$createType19 = sftp$0.FileItem.createFrom;
const $$createType20 = $Create.Array($$createType19);
