// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as account$0 from "./backend/account/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as models$0 from "./backend/models/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as sftp$0 from "./backend/sftp/models.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * AcceptShare accepts an incoming share invite and imports the connection locally.
 */
export function AcceptShare(shareID: string, encryptedKey: string, blobID: string): $CancellablePromise<void> {
    return $Call.ByID(3935935700, shareID, encryptedKey, blobID);
}

/**
 * AccountLogin authenticates against the sync server.
 */
export function AccountLogin(serverURL: string, email: string, password: string): $CancellablePromise<void> {
    return $Call.ByID(1969818985, serverURL, email, password);
}

/**
 * AccountLogout logs out and clears local account data.
 */
export function AccountLogout(): $CancellablePromise<void> {
    return $Call.ByID(1746620394);
}

/**
 * AccountRegister creates a new account on the sync server.
 */
export function AccountRegister(serverURL: string, email: string, password: string): $CancellablePromise<void> {
    return $Call.ByID(1372759869, serverURL, email, password);
}

/**
 * AddTunnel registra un nuevo túnel dinámico en la sesión actual
 */
export function AddTunnel(sessionID: string, localPort: number, remoteHost: string, remotePort: number): $CancellablePromise<models$0.TunnelInfo> {
    return $Call.ByID(1252415046, sessionID, localPort, remoteHost, remotePort).then(($result: any) => {
        return $$createType0($result);
    });
}

/**
 * ApproveHostKey is called by the frontend in response to a host-key-verify event.
 */
export function ApproveHostKey(channelKey: string, approved: boolean): $CancellablePromise<void> {
    return $Call.ByID(2428770811, channelKey, approved);
}

/**
 * CancelShare revokes an outgoing share or declines an incoming share.
 */
export function CancelShare(shareID: string): $CancellablePromise<void> {
    return $Call.ByID(4073839578, shareID);
}

export function CloseSession(sessionID: string): $CancellablePromise<void> {
    return $Call.ByID(1620748453, sessionID);
}

export function ConnectSSH(connectionID: string): $CancellablePromise<string> {
    return $Call.ByID(2333793685, connectionID);
}

/**
 * ConnectSSHVia connects to connectionID routing through jumpHostID as the jump/bastion host.
 */
export function ConnectSSHVia(connectionID: string, jumpHostID: string): $CancellablePromise<string> {
    return $Call.ByID(2333888515, connectionID, jumpHostID);
}

/**
 * CreateConnection encrypts the password before persisting it.
 */
export function CreateConnection(connection: models$0.Connection): $CancellablePromise<void> {
    return $Call.ByID(1454115897, connection);
}

export function CreateFolder(name: string): $CancellablePromise<void> {
    return $Call.ByID(1403526973, name);
}

export function CreateRemoteDirectory(sessionID: string, path: string): $CancellablePromise<void> {
    return $Call.ByID(1468894482, sessionID, path);
}

/**
 * DbConnect opens an SSH-tunneled database connection using native Go drivers.
 */
export function DbConnect(sessionID: string, dbType: string, port: number, user: string, password: string): $CancellablePromise<string> {
    return $Call.ByID(925560863, sessionID, dbType, port, user, password);
}

/**
 * DbDisconnect closes all driver connections and cleans up resources.
 */
export function DbDisconnect(connID: string): $CancellablePromise<void> {
    return $Call.ByID(3946028753, connID);
}

/**
 * DbGetColumns returns column metadata using parameterized queries.
 */
export function DbGetColumns(connID: string, database: string, schema: string, table: string): $CancellablePromise<models$0.QueryColumn[]> {
    return $Call.ByID(417483548, connID, database, schema, table).then(($result: any) => {
        return $$createType2($result);
    });
}

/**
 * DbListDatabases returns available databases over the SSH-tunneled connection.
 */
export function DbListDatabases(connID: string): $CancellablePromise<string[]> {
    return $Call.ByID(3180261039, connID).then(($result: any) => {
        return $$createType3($result);
    });
}

/**
 * DbListSchemas returns schemas for a given database.
 */
export function DbListSchemas(connID: string, database: string): $CancellablePromise<string[]> {
    return $Call.ByID(3889891413, connID, database).then(($result: any) => {
        return $$createType3($result);
    });
}

/**
 * DbListTables returns tables for a database/schema using parameterized queries.
 */
export function DbListTables(connID: string, database: string, schema: string): $CancellablePromise<string[]> {
    return $Call.ByID(3807366482, connID, database, schema).then(($result: any) => {
        return $$createType3($result);
    });
}

/**
 * DbQuery executes arbitrary SQL and returns the result.
 */
export function DbQuery(connID: string, database: string, query: string): $CancellablePromise<models$0.QueryResult> {
    return $Call.ByID(2519177305, connID, database, query).then(($result: any) => {
        return $$createType4($result);
    });
}

export function DeleteConnection(id: string): $CancellablePromise<void> {
    return $Call.ByID(3428926502, id);
}

export function DeleteFolder(id: string): $CancellablePromise<void> {
    return $Call.ByID(127207050, id);
}

export function DeleteRemoteFile(sessionID: string, path: string): $CancellablePromise<void> {
    return $Call.ByID(3455570606, sessionID, path);
}

/**
 * DeleteTunnel elimina un túnel del registro (y lo apaga si está encendido)
 */
export function DeleteTunnel(sessionID: string, tunnelID: string): $CancellablePromise<void> {
    return $Call.ByID(2127640780, sessionID, tunnelID);
}

export function DownloadFile(sessionID: string, remotePath: string, localPath: string): $CancellablePromise<void> {
    return $Call.ByID(764734343, sessionID, remotePath, localPath);
}

/**
 * EditTunnel modifica los parámetros de un túnel existente
 */
export function EditTunnel(sessionID: string, tunnelID: string, localPort: number, remoteHost: string, remotePort: number): $CancellablePromise<models$0.TunnelInfo> {
    return $Call.ByID(3536050427, sessionID, tunnelID, localPort, remoteHost, remotePort).then(($result: any) => {
        return $$createType0($result);
    });
}

/**
 * GetAccountStatus returns the current account and sync status.
 */
export function GetAccountStatus(): $CancellablePromise<account$0.AccountStatus> {
    return $Call.ByID(1877956068).then(($result: any) => {
        return $$createType5($result);
    });
}

/**
 * GetConnectionByID returns a connection with password redacted (use ConnectSSH to connect).
 */
export function GetConnectionByID(id: string): $CancellablePromise<models$0.Connection | null> {
    return $Call.ByID(3650713919, id).then(($result: any) => {
        return $$createType7($result);
    });
}

/**
 * GetConnections returns all connections with passwords redacted.
 * The frontend never receives plaintext passwords.
 */
export function GetConnections(): $CancellablePromise<models$0.Connection[]> {
    return $Call.ByID(1541859132).then(($result: any) => {
        return $$createType8($result);
    });
}

export function GetDatabases(sessionID: string): $CancellablePromise<models$0.DatabaseInfo[]> {
    return $Call.ByID(2970679019, sessionID).then(($result: any) => {
        return $$createType10($result);
    });
}

export function GetDockerContainers(sessionID: string): $CancellablePromise<models$0.DockerContainer[]> {
    return $Call.ByID(3789202067, sessionID).then(($result: any) => {
        return $$createType12($result);
    });
}

/**
 * GetDockerStats returns a one-shot snapshot of CPU and memory usage
 * for all running containers. Non-running containers are absent from the result.
 */
export function GetDockerStats(sessionID: string): $CancellablePromise<models$0.DockerStats[]> {
    return $Call.ByID(438894218, sessionID).then(($result: any) => {
        return $$createType14($result);
    });
}

export function GetFolders(): $CancellablePromise<models$0.Folder[]> {
    return $Call.ByID(452841144).then(($result: any) => {
        return $$createType16($result);
    });
}

/**
 * GetIncomingShares returns pending/accepted share invites.
 */
export function GetIncomingShares(): $CancellablePromise<account$0.ShareInfo[]> {
    return $Call.ByID(2759342007).then(($result: any) => {
        return $$createType18($result);
    });
}

export function GetListeningPorts(sessionID: string): $CancellablePromise<models$0.PortInfo[]> {
    return $Call.ByID(3826983416, sessionID).then(($result: any) => {
        return $$createType20($result);
    });
}

/**
 * GetPublicKey returns this account's X25519 public key.
 */
export function GetPublicKey(): $CancellablePromise<string> {
    return $Call.ByID(1425211265);
}

/**
 * GetSentShares returns share invites created by the current user.
 */
export function GetSentShares(): $CancellablePromise<account$0.ShareInfo[]> {
    return $Call.ByID(1200468861).then(($result: any) => {
        return $$createType18($result);
    });
}

export function GetSystemStats(sessionID: string): $CancellablePromise<$models.SystemStats | null> {
    return $Call.ByID(549671605, sessionID).then(($result: any) => {
        return $$createType22($result);
    });
}

/**
 * GetTunnels obtiene la lista de túneles dinámicos guardados para la sesión activa
 */
export function GetTunnels(sessionID: string): $CancellablePromise<models$0.TunnelInfo[]> {
    return $Call.ByID(2458647734, sessionID).then(($result: any) => {
        return $$createType23($result);
    });
}

/**
 * GetVirtualBoxVMs lists all VMs on the remote host.
 * Returns an error if VBoxManage is not installed.
 */
export function GetVirtualBoxVMs(sessionID: string): $CancellablePromise<models$0.VMInfo[]> {
    return $Call.ByID(3094937307, sessionID).then(($result: any) => {
        return $$createType25($result);
    });
}

/**
 * IsVaultLocked returns true if the master key is not loaded in memory.
 */
export function IsVaultLocked(): $CancellablePromise<boolean> {
    return $Call.ByID(4122673697);
}

/**
 * IsVaultSetup returns true if a master password salt has been stored.
 */
export function IsVaultSetup(): $CancellablePromise<boolean> {
    return $Call.ByID(3586881096);
}

/**
 * IsVirtualBoxAvailable checks whether VBoxManage is installed on the remote host.
 */
export function IsVirtualBoxAvailable(sessionID: string): $CancellablePromise<boolean> {
    return $Call.ByID(2211996688, sessionID);
}

export function ListDirectory(sessionID: string, path: string): $CancellablePromise<sftp$0.FileItem[]> {
    return $Call.ByID(3882022436, sessionID, path).then(($result: any) => {
        return $$createType27($result);
    });
}

export function ListSessions(): $CancellablePromise<string[]> {
    return $Call.ByID(827108744).then(($result: any) => {
        return $$createType3($result);
    });
}

/**
 * LockVault clears the master key from memory.
 */
export function LockVault(): $CancellablePromise<void> {
    return $Call.ByID(563136070);
}

/**
 * OpenDbExplorerWindow abre el explorador de BD en una ventana del navegador del sistema
 */
export function OpenDbExplorerWindow(sessionID: string, dbType: string, port: number): $CancellablePromise<void> {
    return $Call.ByID(2917079268, sessionID, dbType, port);
}

/**
 * OpenDockerLogWindow abre los logs del contenedor en una ventana del navegador del sistema
 */
export function OpenDockerLogWindow(sessionID: string, containerID: string, containerName: string): $CancellablePromise<void> {
    return $Call.ByID(1038673189, sessionID, containerID, containerName);
}

export function ReadRemoteFile(sessionID: string, path: string): $CancellablePromise<string> {
    return $Call.ByID(4253671989, sessionID, path);
}

export function RenameRemoteFile(sessionID: string, oldPath: string, newPath: string): $CancellablePromise<void> {
    return $Call.ByID(3344013991, sessionID, oldPath, newPath);
}

export function ResizeTerminal(sessionID: string, rows: number, cols: number): $CancellablePromise<void> {
    return $Call.ByID(1887984285, sessionID, rows, cols);
}

export function SaveRemoteFile(sessionID: string, path: string, content: string): $CancellablePromise<void> {
    return $Call.ByID(4146041056, sessionID, path, content);
}

export function SendInput(sessionID: string, data: string): $CancellablePromise<void> {
    return $Call.ByID(2049385733, sessionID, data);
}

/**
 * SetupMasterPassword creates the vault for the first time.
 */
export function SetupMasterPassword(password: string): $CancellablePromise<void> {
    return $Call.ByID(429511141, password);
}

/**
 * ShareConnection shares a connection with another Condui user by email.
 */
export function ShareConnection(connectionID: string, recipientEmail: string, readOnly: boolean, includePassword: boolean): $CancellablePromise<void> {
    return $Call.ByID(3307276152, connectionID, recipientEmail, readOnly, includePassword);
}

/**
 * StartDockerLogs abre docker logs -f en el contenedor y emite cada línea como evento Wails
 */
export function StartDockerLogs(sessionID: string, containerID: string): $CancellablePromise<void> {
    return $Call.ByID(2915829348, sessionID, containerID);
}

/**
 * StopDockerLogs detiene el stream de logs cerrando la sesión SSH
 */
export function StopDockerLogs(sessionID: string, containerID: string): $CancellablePromise<void> {
    return $Call.ByID(3177717606, sessionID, containerID);
}

/**
 * SyncNow reconciles local and remote connections, then uploads the merged set.
 */
export function SyncNow(): $CancellablePromise<void> {
    return $Call.ByID(2954670258);
}

export function TestConnection(connectionID: string): $CancellablePromise<void> {
    return $Call.ByID(1257240193, connectionID);
}

/**
 * TestConnectionParams tests a connection using raw params without requiring a saved record.
 */
export function TestConnectionParams(host: string, port: number, username: string, authType: string, password: string, privateKeyPath: string, jumpHostID: string): $CancellablePromise<void> {
    return $Call.ByID(2464955863, host, port, username, authType, password, privateKeyPath, jumpHostID);
}

/**
 * ToggleContainer ejecuta las acciones vitales: start, stop o restart
 */
export function ToggleContainer(sessionID: string, containerID: string, action: string): $CancellablePromise<string> {
    return $Call.ByID(2722533264, sessionID, containerID, action);
}

/**
 * ToggleTunnel enciende o apaga el túnel SSH local port forwarding de forma asíncrona
 */
export function ToggleTunnel(sessionID: string, tunnelID: string, localPort: number, remoteHost: string, remotePort: number, activate: boolean): $CancellablePromise<void> {
    return $Call.ByID(1290322095, sessionID, tunnelID, localPort, remoteHost, remotePort, activate);
}

/**
 * UnlockVault derives the master key from password and verifies it.
 */
export function UnlockVault(password: string): $CancellablePromise<void> {
    return $Call.ByID(2387715367, password);
}

/**
 * UpdateConnection encrypts the password before updating.
 */
export function UpdateConnection(connection: models$0.Connection): $CancellablePromise<void> {
    return $Call.ByID(619964812, connection);
}

export function UpdateFolder(id: string, name: string): $CancellablePromise<void> {
    return $Call.ByID(4154189448, id, name);
}

export function UploadFile(sessionID: string, remoteDirectory: string): $CancellablePromise<void> {
    return $Call.ByID(3284072274, sessionID, remoteDirectory);
}

/**
 * VirtualBoxAction performs a lifecycle action on a VM.
 * Valid actions: start-gui, start-headless, stop-acpi, stop-force,
 * pause, resume, reset, savestate.
 */
export function VirtualBoxAction(sessionID: string, vmName: string, action: string): $CancellablePromise<string> {
    return $Call.ByID(196318823, sessionID, vmName, action);
}

// Private type creation functions
const $$createType0 = models$0.TunnelInfo.createFrom;
const $$createType1 = models$0.QueryColumn.createFrom;
const $$createType2 = $Create.Array($$createType1);
const $$createType3 = $Create.Array($Create.Any);
const $$createType4 = models$0.QueryResult.createFrom;
const $$createType5 = account$0.AccountStatus.createFrom;
const $$createType6 = models$0.Connection.createFrom;
const $$createType7 = $Create.Nullable($$createType6);
const $$createType8 = $Create.Array($$createType6);
const $$createType9 = models$0.DatabaseInfo.createFrom;
const $$createType10 = $Create.Array($$createType9);
const $$createType11 = models$0.DockerContainer.createFrom;
const $$createType12 = $Create.Array($$createType11);
const $$createType13 = models$0.DockerStats.createFrom;
const $$createType14 = $Create.Array($$createType13);
const $$createType15 = models$0.Folder.createFrom;
const $$createType16 = $Create.Array($$createType15);
const $$createType17 = account$0.ShareInfo.createFrom;
const $$createType18 = $Create.Array($$createType17);
const $$createType19 = models$0.PortInfo.createFrom;
const $$createType20 = $Create.Array($$createType19);
const $$createType21 = $models.SystemStats.createFrom;
const $$createType22 = $Create.Nullable($$createType21);
const $$createType23 = $Create.Array($$createType0);
const $$createType24 = models$0.VMInfo.createFrom;
const $$createType25 = $Create.Array($$createType24);
const $$createType26 = sftp$0.FileItem.createFrom;
const $$createType27 = $Create.Array($$createType26);
