// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as models$0 from "./backend/models/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as sftp$0 from "./backend/sftp/models.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * AddTunnel registra un nuevo túnel dinámico en la sesión actual
 */
export function AddTunnel(sessionID: string, localPort: number, remoteHost: string, remotePort: number): $CancellablePromise<models$0.TunnelInfo> {
    return $Call.ByID(1252415046, sessionID, localPort, remoteHost, remotePort).then(($result: any) => {
        return $$createType0($result);
    });
}

export function CloseSession(sessionID: string): $CancellablePromise<void> {
    return $Call.ByID(1620748453, sessionID);
}

export function ConnectSSH(connectionID: string): $CancellablePromise<string> {
    return $Call.ByID(2333793685, connectionID);
}

export function CreateConnection(connection: models$0.Connection): $CancellablePromise<void> {
    return $Call.ByID(1454115897, connection);
}

export function CreateFolder(name: string): $CancellablePromise<void> {
    return $Call.ByID(1403526973, name);
}

export function CreateRemoteDirectory(sessionID: string, path: string): $CancellablePromise<void> {
    return $Call.ByID(1468894482, sessionID, path);
}

/**
 * DbConnect opens an SSH-tunneled database connection using native Go drivers.
 */
export function DbConnect(sessionID: string, dbType: string, port: number, user: string, password: string): $CancellablePromise<string> {
    return $Call.ByID(925560863, sessionID, dbType, port, user, password);
}

/**
 * DbDisconnect closes all driver connections and cleans up resources.
 */
export function DbDisconnect(connID: string): $CancellablePromise<void> {
    return $Call.ByID(3946028753, connID);
}

/**
 * DbGetColumns returns column metadata using parameterized queries.
 */
export function DbGetColumns(connID: string, database: string, schema: string, table: string): $CancellablePromise<models$0.QueryColumn[]> {
    return $Call.ByID(417483548, connID, database, schema, table).then(($result: any) => {
        return $$createType2($result);
    });
}

/**
 * DbListDatabases returns available databases over the SSH-tunneled connection.
 */
export function DbListDatabases(connID: string): $CancellablePromise<string[]> {
    return $Call.ByID(3180261039, connID).then(($result: any) => {
        return $$createType3($result);
    });
}

/**
 * DbListSchemas returns schemas for a given database.
 */
export function DbListSchemas(connID: string, database: string): $CancellablePromise<string[]> {
    return $Call.ByID(3889891413, connID, database).then(($result: any) => {
        return $$createType3($result);
    });
}

/**
 * DbListTables returns tables for a database/schema using parameterized queries.
 */
export function DbListTables(connID: string, database: string, schema: string): $CancellablePromise<string[]> {
    return $Call.ByID(3807366482, connID, database, schema).then(($result: any) => {
        return $$createType3($result);
    });
}

/**
 * DbQuery executes arbitrary SQL and returns the result.
 */
export function DbQuery(connID: string, database: string, query: string): $CancellablePromise<models$0.QueryResult> {
    return $Call.ByID(2519177305, connID, database, query).then(($result: any) => {
        return $$createType4($result);
    });
}

export function DeleteConnection(id: string): $CancellablePromise<void> {
    return $Call.ByID(3428926502, id);
}

export function DeleteFolder(id: string): $CancellablePromise<void> {
    return $Call.ByID(127207050, id);
}

export function DeleteRemoteFile(sessionID: string, path: string): $CancellablePromise<void> {
    return $Call.ByID(3455570606, sessionID, path);
}

/**
 * DeleteTunnel elimina un túnel del registro (y lo apaga si está encendido)
 */
export function DeleteTunnel(sessionID: string, tunnelID: string): $CancellablePromise<void> {
    return $Call.ByID(2127640780, sessionID, tunnelID);
}

export function DownloadFile(sessionID: string, remotePath: string, localPath: string): $CancellablePromise<void> {
    return $Call.ByID(764734343, sessionID, remotePath, localPath);
}

/**
 * EditTunnel modifica los parámetros de un túnel existente
 */
export function EditTunnel(sessionID: string, tunnelID: string, localPort: number, remoteHost: string, remotePort: number): $CancellablePromise<models$0.TunnelInfo> {
    return $Call.ByID(3536050427, sessionID, tunnelID, localPort, remoteHost, remotePort).then(($result: any) => {
        return $$createType0($result);
    });
}

export function GetConnectionByID(id: string): $CancellablePromise<models$0.Connection | null> {
    return $Call.ByID(3650713919, id).then(($result: any) => {
        return $$createType6($result);
    });
}

export function GetConnections(): $CancellablePromise<models$0.Connection[]> {
    return $Call.ByID(1541859132).then(($result: any) => {
        return $$createType7($result);
    });
}

export function GetDatabases(sessionID: string): $CancellablePromise<models$0.DatabaseInfo[]> {
    return $Call.ByID(2970679019, sessionID).then(($result: any) => {
        return $$createType9($result);
    });
}

export function GetDockerContainers(sessionID: string): $CancellablePromise<models$0.DockerContainer[]> {
    return $Call.ByID(3789202067, sessionID).then(($result: any) => {
        return $$createType11($result);
    });
}

export function GetFolders(): $CancellablePromise<models$0.Folder[]> {
    return $Call.ByID(452841144).then(($result: any) => {
        return $$createType13($result);
    });
}

export function GetListeningPorts(sessionID: string): $CancellablePromise<models$0.PortInfo[]> {
    return $Call.ByID(3826983416, sessionID).then(($result: any) => {
        return $$createType15($result);
    });
}

export function GetSystemStats(sessionID: string): $CancellablePromise<$models.SystemStats | null> {
    return $Call.ByID(549671605, sessionID).then(($result: any) => {
        return $$createType17($result);
    });
}

/**
 * GetTunnels obtiene la lista de túneles dinámicos guardados para la sesión activa
 */
export function GetTunnels(sessionID: string): $CancellablePromise<models$0.TunnelInfo[]> {
    return $Call.ByID(2458647734, sessionID).then(($result: any) => {
        return $$createType18($result);
    });
}

export function ListDirectory(sessionID: string, path: string): $CancellablePromise<sftp$0.FileItem[]> {
    return $Call.ByID(3882022436, sessionID, path).then(($result: any) => {
        return $$createType20($result);
    });
}

export function ListSessions(): $CancellablePromise<string[]> {
    return $Call.ByID(827108744).then(($result: any) => {
        return $$createType3($result);
    });
}

/**
 * OpenDbExplorerWindow abre el explorador de BD en una ventana del navegador del sistema
 */
export function OpenDbExplorerWindow(sessionID: string, dbType: string, port: number): $CancellablePromise<void> {
    return $Call.ByID(2917079268, sessionID, dbType, port);
}

/**
 * OpenDockerLogWindow abre los logs del contenedor en una ventana del navegador del sistema
 */
export function OpenDockerLogWindow(sessionID: string, containerID: string, containerName: string): $CancellablePromise<void> {
    return $Call.ByID(1038673189, sessionID, containerID, containerName);
}

export function ReadRemoteFile(sessionID: string, path: string): $CancellablePromise<string> {
    return $Call.ByID(4253671989, sessionID, path);
}

export function RenameRemoteFile(sessionID: string, oldPath: string, newPath: string): $CancellablePromise<void> {
    return $Call.ByID(3344013991, sessionID, oldPath, newPath);
}

export function ResizeTerminal(sessionID: string, rows: number, cols: number): $CancellablePromise<void> {
    return $Call.ByID(1887984285, sessionID, rows, cols);
}

export function SaveRemoteFile(sessionID: string, path: string, content: string): $CancellablePromise<void> {
    return $Call.ByID(4146041056, sessionID, path, content);
}

export function SendInput(sessionID: string, data: string): $CancellablePromise<void> {
    return $Call.ByID(2049385733, sessionID, data);
}

/**
 * StartDockerLogs abre docker logs -f en el contenedor y emite cada línea como evento Wails
 */
export function StartDockerLogs(sessionID: string, containerID: string): $CancellablePromise<void> {
    return $Call.ByID(2915829348, sessionID, containerID);
}

/**
 * StopDockerLogs detiene el stream de logs cerrando la sesión SSH
 */
export function StopDockerLogs(sessionID: string, containerID: string): $CancellablePromise<void> {
    return $Call.ByID(3177717606, sessionID, containerID);
}

/**
 * ToggleContainer ejecuta las acciones vitales: start, stop o restart
 */
export function ToggleContainer(sessionID: string, containerID: string, action: string): $CancellablePromise<string> {
    return $Call.ByID(2722533264, sessionID, containerID, action);
}

/**
 * ToggleTunnel enciende o apaga el túnel SSH local port forwarding de forma asíncrona
 */
export function ToggleTunnel(sessionID: string, tunnelID: string, localPort: number, remoteHost: string, remotePort: number, activate: boolean): $CancellablePromise<void> {
    return $Call.ByID(1290322095, sessionID, tunnelID, localPort, remoteHost, remotePort, activate);
}

export function UpdateConnection(connection: models$0.Connection): $CancellablePromise<void> {
    return $Call.ByID(619964812, connection);
}

export function UpdateFolder(id: string, name: string): $CancellablePromise<void> {
    return $Call.ByID(4154189448, id, name);
}

export function UploadFile(sessionID: string, remoteDirectory: string): $CancellablePromise<void> {
    return $Call.ByID(3284072274, sessionID, remoteDirectory);
}

// Private type creation functions
const $$createType0 = models$0.TunnelInfo.createFrom;
const $$createType1 = models$0.QueryColumn.createFrom;
const $$createType2 = $Create.Array($$createType1);
const $$createType3 = $Create.Array($Create.Any);
const $$createType4 = models$0.QueryResult.createFrom;
const $$createType5 = models$0.Connection.createFrom;
const $$createType6 = $Create.Nullable($$createType5);
const $$createType7 = $Create.Array($$createType5);
const $$createType8 = models$0.DatabaseInfo.createFrom;
const $$createType9 = $Create.Array($$createType8);
const $$createType10 = models$0.DockerContainer.createFrom;
const $$createType11 = $Create.Array($$createType10);
const $$createType12 = models$0.Folder.createFrom;
const $$createType13 = $Create.Array($$createType12);
const $$createType14 = models$0.PortInfo.createFrom;
const $$createType15 = $Create.Array($$createType14);
const $$createType16 = $models.SystemStats.createFrom;
const $$createType17 = $Create.Nullable($$createType16);
const $$createType18 = $Create.Array($$createType0);
const $$createType19 = sftp$0.FileItem.createFrom;
const $$createType20 = $Create.Array($$createType19);
