// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

export class SystemStats {
    /**
     * Creates a new SystemStats instance.
     * @param {Partial<SystemStats>} [$$source = {}] - The source object to create the SystemStats.
     */
    constructor($$source = {}) {
        if (!("cpuPercent" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["cpuPercent"] = 0;
        }
        if (!("memUsedGB" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["memUsedGB"] = 0;
        }
        if (!("memFreeGB" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["memFreeGB"] = 0;
        }
        if (!("memTotalGB" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["memTotalGB"] = 0;
        }
        if (!("diskUsedGB" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["diskUsedGB"] = 0;
        }
        if (!("diskFreeGB" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["diskFreeGB"] = 0;
        }
        if (!("diskTotalGB" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["diskTotalGB"] = 0;
        }
        if (!("uptimeSecs" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["uptimeSecs"] = 0;
        }
        if (!("netRxBps" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["netRxBps"] = 0;
        }
        if (!("netTxBps" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["netTxBps"] = 0;
        }
        if (!("diskReadBps" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["diskReadBps"] = 0;
        }
        if (!("diskWriteBps" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["diskWriteBps"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SystemStats instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {SystemStats}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new SystemStats(/** @type {Partial<SystemStats>} */($$parsedSource));
    }
}
