// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

export class SystemStats {
    "cpuPercent": number;
    "memUsedGB": number;
    "memFreeGB": number;
    "memTotalGB": number;
    "diskUsedGB": number;
    "diskFreeGB": number;
    "diskTotalGB": number;
    "uptimeSecs": number;
    "netRxBps": number;
    "netTxBps": number;
    "diskReadBps": number;
    "diskWriteBps": number;

    /** Creates a new SystemStats instance. */
    constructor($$source: Partial<SystemStats> = {}) {
        if (!("cpuPercent" in $$source)) {
            this["cpuPercent"] = 0;
        }
        if (!("memUsedGB" in $$source)) {
            this["memUsedGB"] = 0;
        }
        if (!("memFreeGB" in $$source)) {
            this["memFreeGB"] = 0;
        }
        if (!("memTotalGB" in $$source)) {
            this["memTotalGB"] = 0;
        }
        if (!("diskUsedGB" in $$source)) {
            this["diskUsedGB"] = 0;
        }
        if (!("diskFreeGB" in $$source)) {
            this["diskFreeGB"] = 0;
        }
        if (!("diskTotalGB" in $$source)) {
            this["diskTotalGB"] = 0;
        }
        if (!("uptimeSecs" in $$source)) {
            this["uptimeSecs"] = 0;
        }
        if (!("netRxBps" in $$source)) {
            this["netRxBps"] = 0;
        }
        if (!("netTxBps" in $$source)) {
            this["netTxBps"] = 0;
        }
        if (!("diskReadBps" in $$source)) {
            this["diskReadBps"] = 0;
        }
        if (!("diskWriteBps" in $$source)) {
            this["diskWriteBps"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SystemStats instance from a string or object.
     */
    static createFrom($$source: any = {}): SystemStats {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new SystemStats($$parsedSource as Partial<SystemStats>);
    }
}
