// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as time$0 from "../../../time/models.js";

export class FileItem {
    "name": string;
    "path": string;
    "isDirectory": boolean;
    "size": number;
    "mode": string;
    "modTime": time$0.Time;

    /** Creates a new FileItem instance. */
    constructor($$source: Partial<FileItem> = {}) {
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("path" in $$source)) {
            this["path"] = "";
        }
        if (!("isDirectory" in $$source)) {
            this["isDirectory"] = false;
        }
        if (!("size" in $$source)) {
            this["size"] = 0;
        }
        if (!("mode" in $$source)) {
            this["mode"] = "";
        }
        if (!("modTime" in $$source)) {
            this["modTime"] = null;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new FileItem instance from a string or object.
     */
    static createFrom($$source: any = {}): FileItem {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new FileItem($$parsedSource as Partial<FileItem>);
    }
}
