// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

export class AccountStatus {
    "loggedIn": boolean;
    "email": string;
    "tier": string;
    "serverUrl": string;
    "lastSync": string;

    /** Creates a new AccountStatus instance. */
    constructor($$source: Partial<AccountStatus> = {}) {
        if (!("loggedIn" in $$source)) {
            this["loggedIn"] = false;
        }
        if (!("email" in $$source)) {
            this["email"] = "";
        }
        if (!("tier" in $$source)) {
            this["tier"] = "";
        }
        if (!("serverUrl" in $$source)) {
            this["serverUrl"] = "";
        }
        if (!("lastSync" in $$source)) {
            this["lastSync"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new AccountStatus instance from a string or object.
     */
    static createFrom($$source: any = {}): AccountStatus {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new AccountStatus($$parsedSource as Partial<AccountStatus>);
    }
}

export class ShareInfo {
    "id": string;
    "ownerEmail": string;
    "blobId": string;
    "permissions": string;
    "status": string;

    /** Creates a new ShareInfo instance. */
    constructor($$source: Partial<ShareInfo> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("ownerEmail" in $$source)) {
            this["ownerEmail"] = "";
        }
        if (!("blobId" in $$source)) {
            this["blobId"] = "";
        }
        if (!("permissions" in $$source)) {
            this["permissions"] = "";
        }
        if (!("status" in $$source)) {
            this["status"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ShareInfo instance from a string or object.
     */
    static createFrom($$source: any = {}): ShareInfo {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ShareInfo($$parsedSource as Partial<ShareInfo>);
    }
}
